//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherUtilities.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileWatcherUtilities.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logFilePath.
        /// </summary>
        internal static string ConfigurationFieldLogFilePath {
            get {
                return ResourceManager.GetString("ConfigurationFieldLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logUpdateInterval.
        /// </summary>
        internal static string ConfigurationFieldLogUpdateInterval {
            get {
                return ResourceManager.GetString("ConfigurationFieldLogUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queueTrimInterval.
        /// </summary>
        internal static string ConfigurationFieldQueueTrimInterval {
            get {
                return ResourceManager.GetString("ConfigurationFieldQueueTrimInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateInterval.
        /// </summary>
        internal static string ConfigurationFieldUpdateInterval {
            get {
                return ResourceManager.GetString("ConfigurationFieldUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlApplicationOptionsFilePath.
        /// </summary>
        internal static string ConfigurationFieldXmlApplicationOptionsFilePath {
            get {
                return ResourceManager.GetString("ConfigurationFieldXmlApplicationOptionsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlConfigurationFilePath.
        /// </summary>
        internal static string ConfigurationFieldXmlConfigurationFilePath {
            get {
                return ResourceManager.GetString("ConfigurationFieldXmlConfigurationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlSchemaApplicationOptionsFilePath.
        /// </summary>
        internal static string ConfigurationFieldXmlSchemaApplicationOptionsFilePath {
            get {
                return ResourceManager.GetString("ConfigurationFieldXmlSchemaApplicationOptionsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlSchemaConfigurationFilePath.
        /// </summary>
        internal static string ConfigurationFieldXmlSchemaConfigurationFilePath {
            get {
                return ResourceManager.GetString("ConfigurationFieldXmlSchemaConfigurationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwatcher.log.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwoptions.xml.
        /// </summary>
        internal static string XmlApplicationOptionsFileName {
            get {
                return ResourceManager.GetString("XmlApplicationOptionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwatcher.xml.
        /// </summary>
        internal static string XmlConfigFileName {
            get {
                return ResourceManager.GetString("XmlConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwoptions.xsd.
        /// </summary>
        internal static string XmlSchemaApplicationOptionsFileName {
            get {
                return ResourceManager.GetString("XmlSchemaApplicationOptionsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwatcher.xsd.
        /// </summary>
        internal static string XmlSchemaFileName {
            get {
                return ResourceManager.GetString("XmlSchemaFileName", resourceCulture);
            }
        }
    }
}
