//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherUtilities.FileWatcherSimple.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileWatcherUtilities.FileWatcherSimple.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string AboutLabelVersion {
            get {
                return ResourceManager.GetString("AboutLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Jussi Hiltunen 2006-2013.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the directory to watch.
        /// </summary>
        internal static string DialogDescriptionPathToWatch {
            get {
                return ResourceManager.GetString("DialogDescriptionPathToWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process working directory.
        /// </summary>
        internal static string DialogDescriptionWorkingDirectory {
            get {
                return ResourceManager.GetString("DialogDescriptionWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs |*.exe|All files (*.*)|*.*.
        /// </summary>
        internal static string ExecutableFilter {
            get {
                return ResourceManager.GetString("ExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file watcher?
        ///
        ///{0}.
        /// </summary>
        internal static string MessageAreYouSureYouWantToDeleteFileWatcher {
            get {
                return ResourceManager.GetString("MessageAreYouSureYouWantToDeleteFileWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Watcher Simple.
        /// </summary>
        internal static string MessageBoxCaptionApplication {
            get {
                return ResourceManager.GetString("MessageBoxCaptionApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBoxCaptionError {
            get {
                return ResourceManager.GetString("MessageBoxCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open application log file..
        /// </summary>
        internal static string MessageCannotOpenLogFile {
            get {
                return ResourceManager.GetString("MessageCannotOpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file watcher configuration file: {0}.
        /// </summary>
        internal static string MessageFileWatcherConfigurationError {
            get {
                return ResourceManager.GetString("MessageFileWatcherConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help cannot be viewed due to an error..
        /// </summary>
        internal static string MessageHelpCannotBeViewed {
            get {
                return ResourceManager.GetString("MessageHelpCannotBeViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License cannot be viewed due to an error..
        /// </summary>
        internal static string MessageLicenseCannotBeViewed {
            get {
                return ResourceManager.GetString("MessageLicenseCannotBeViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: .
        /// </summary>
        internal static string MessageUnexpectedError {
            get {
                return ResourceManager.GetString("MessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: .
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop running file watchers before exiting the application..
        /// </summary>
        internal static string StopControllerMessage {
            get {
                return ResourceManager.GetString("StopControllerMessage", resourceCulture);
            }
        }
    }
}
