//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherUtilities.Logger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileWatcherUtilities.Logger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid log file path..
        /// </summary>
        internal static string ArgumentExceptionInvalidPath {
            get {
                return ResourceManager.GetString("ArgumentExceptionInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message type..
        /// </summary>
        internal static string ArgumentExceptionMessageType {
            get {
                return ResourceManager.GetString("ArgumentExceptionMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System generated.
        /// </summary>
        internal static string ChangeTypeSystemGenerated {
            get {
                return ResourceManager.GetString("ChangeTypeSystemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Buffer error in &apos;{2}&apos; daemon. Reason: {3}.
        /// </summary>
        internal static string MessageBufferError {
            get {
                return ResourceManager.GetString("MessageBufferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; is stopped. Path &apos;{3}&apos; is invalid..
        /// </summary>
        internal static string MessageDaemonPathError {
            get {
                return ResourceManager.GetString("MessageDaemonPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; is started..
        /// </summary>
        internal static string MessageDaemonStarted {
            get {
                return ResourceManager.GetString("MessageDaemonStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; is starting..
        /// </summary>
        internal static string MessageDaemonStarting {
            get {
                return ResourceManager.GetString("MessageDaemonStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; is stopped..
        /// </summary>
        internal static string MessageDaemonStopped {
            get {
                return ResourceManager.GetString("MessageDaemonStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] File or folder {2} &apos;{3}&apos;..
        /// </summary>
        internal static string MessageFileSystemChange {
            get {
                return ResourceManager.GetString("MessageFileSystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; was recycled. Reason: {3}.
        /// </summary>
        internal static string MessageFileWatcherRecycle {
            get {
                return ResourceManager.GetString("MessageFileWatcherRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found..
        /// </summary>
        internal static string MessageFileWatcherRecycleReasonDirectoryNotFound {
            get {
                return ResourceManager.GetString("MessageFileWatcherRecycleReasonDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageFileWatcherRecycleReasonError {
            get {
                return ResourceManager.GetString("MessageFileWatcherRecycleReasonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        internal static string MessageFileWatcherRecycleReasonRecycle {
            get {
                return ResourceManager.GetString("MessageFileWatcherRecycleReasonRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Process was canceled for &apos;{2}&apos; daemon. Reason: {3} Path: &apos;{4}&apos;.
        /// </summary>
        internal static string MessageProcessCanceled {
            get {
                return ResourceManager.GetString("MessageProcessCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        internal static string MessageProcessCanceledReasonFileIsMissing {
            get {
                return ResourceManager.GetString("MessageProcessCanceledReasonFileIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file lock test failed..
        /// </summary>
        internal static string MessageProcessCanceledReasonFileLockTestFailed {
            get {
                return ResourceManager.GetString("MessageProcessCanceledReasonFileLockTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The renaming of the file failed..
        /// </summary>
        internal static string MessageProcessCanceledReasonRenameFailed {
            get {
                return ResourceManager.GetString("MessageProcessCanceledReasonRenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Error in process started by &apos;{2}&apos; daemon. Reason: {3}.
        /// </summary>
        internal static string MessageProcessError {
            get {
                return ResourceManager.GetString("MessageProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; process error data: &apos;{3}&apos;..
        /// </summary>
        internal static string MessageProcessErrorData {
            get {
                return ResourceManager.GetString("MessageProcessErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Process {2} started by &apos;{3}&apos; daemon has exited with exit code {4}..
        /// </summary>
        internal static string MessageProcessExited {
            get {
                return ResourceManager.GetString("MessageProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; process output data: &apos;{3}&apos;..
        /// </summary>
        internal static string MessageProcessOutputData {
            get {
                return ResourceManager.GetString("MessageProcessOutputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; started &apos;{3}&apos; {4} process with &apos;{5}&apos; arguments and with &apos;{6}&apos; verb. Processes to run: {7}..
        /// </summary>
        internal static string MessageProcessStarted {
            get {
                return ResourceManager.GetString("MessageProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Search error in &apos;{2}&apos; daemon. Reason: {3}.
        /// </summary>
        internal static string MessageSearchError {
            get {
                return ResourceManager.GetString("MessageSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] Daemon &apos;{2}&apos; is searching folder {3}..
        /// </summary>
        internal static string MessageSearchProgess {
            get {
                return ResourceManager.GetString("MessageSearchProgess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] [{3}] Daemon &apos;{2}&apos; is about to call a service..
        /// </summary>
        internal static string MessageServiceBeginCall {
            get {
                return ResourceManager.GetString("MessageServiceBeginCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] [{3}] Daemon &apos;{2}&apos; called a service and it returned: &apos;{4}&apos;.
        /// </summary>
        internal static string MessageServiceCalled {
            get {
                return ResourceManager.GetString("MessageServiceCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] [{3}] Error in service called by &apos;{2}&apos; daemon. Severity: {4} ErrorCode: {5} Reason: {6} ErrorId: {7} .
        /// </summary>
        internal static string MessageServiceDefaultError {
            get {
                return ResourceManager.GetString("MessageServiceDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] [{3}] Error in service called by &apos;{2}&apos; daemon. Reason: {4}.
        /// </summary>
        internal static string MessageServiceError {
            get {
                return ResourceManager.GetString("MessageServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service did not send the error information..
        /// </summary>
        internal static string MessageServiceErrorDataIsMissing {
            get {
                return ResourceManager.GetString("MessageServiceErrorDataIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1}] [{3}] Daemon &apos;{2}&apos; failed to create a service proxy..
        /// </summary>
        internal static string MessageServiceProxyCreationError {
            get {
                return ResourceManager.GetString("MessageServiceProxyCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changed (system generated).
        /// </summary>
        internal static string MessageSystemGenerated {
            get {
                return ResourceManager.GetString("MessageSystemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageTypeError {
            get {
                return ResourceManager.GetString("MessageTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MessageTypeInfo {
            get {
                return ResourceManager.GetString("MessageTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        internal static string MessageTypeWarn {
            get {
                return ResourceManager.GetString("MessageTypeWarn", resourceCulture);
            }
        }
    }
}
