//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherUtilities.Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileWatcherUtilities.Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call service and start process are both selected..
        /// </summary>
        internal static string ArgumentExceptionCallServiceAndStartProcessAreBothSelected {
            get {
                return ResourceManager.GetString("ArgumentExceptionCallServiceAndStartProcessAreBothSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed regular expression filter is invalid..
        /// </summary>
        internal static string ArgumentExceptionChangedFilter {
            get {
                return ResourceManager.GetString("ArgumentExceptionChangedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created regular expression filter is invalid..
        /// </summary>
        internal static string ArgumentExceptionCreatedFilter {
            get {
                return ResourceManager.GetString("ArgumentExceptionCreatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon names are not unique..
        /// </summary>
        internal static string ArgumentExceptionDaemonNameAreNotUnique {
            get {
                return ResourceManager.GetString("ArgumentExceptionDaemonNameAreNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher daemon name is not unique..
        /// </summary>
        internal static string ArgumentExceptionDaemonNameIsNotUnique {
            get {
                return ResourceManager.GetString("ArgumentExceptionDaemonNameIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon name is null..
        /// </summary>
        internal static string ArgumentExceptionDaemonNameIsNull {
            get {
                return ResourceManager.GetString("ArgumentExceptionDaemonNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon not found..
        /// </summary>
        internal static string ArgumentExceptionDaemonNotFound {
            get {
                return ResourceManager.GetString("ArgumentExceptionDaemonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted regular expression filter is invalid..
        /// </summary>
        internal static string ArgumentExceptionDeletedFilter {
            get {
                return ResourceManager.GetString("ArgumentExceptionDeletedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate argument escape string..
        /// </summary>
        internal static string ArgumentExceptionDuplicateArgumentEscapeString {
            get {
                return ResourceManager.GetString("ArgumentExceptionDuplicateArgumentEscapeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate daemon name..
        /// </summary>
        internal static string ArgumentExceptionDuplicateDaemonName {
            get {
                return ResourceManager.GetString("ArgumentExceptionDuplicateDaemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher process file name is empty..
        /// </summary>
        internal static string ArgumentExceptionFileNameIsEmpty {
            get {
                return ResourceManager.GetString("ArgumentExceptionFileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated event file name regular expression filter is invalid..
        /// </summary>
        internal static string ArgumentExceptionGeneratedEventFileNameFilter {
            get {
                return ResourceManager.GetString("ArgumentExceptionGeneratedEventFileNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is Guid.Empty..
        /// </summary>
        internal static string ArgumentExceptionIdIsEmpty {
            get {
                return ResourceManager.GetString("ArgumentExceptionIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password may not be specified when using shell execute..
        /// </summary>
        internal static string ArgumentExceptionPasswordAndShellExecute {
            get {
                return ResourceManager.GetString("ArgumentExceptionPasswordAndShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher path does not exist..
        /// </summary>
        internal static string ArgumentExceptionPathDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentExceptionPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue trim interval cannot be negative..
        /// </summary>
        internal static string ArgumentExceptionQueueTrimIntervalCannotBeNegative {
            get {
                return ResourceManager.GetString("ArgumentExceptionQueueTrimIntervalCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect error may not be selected when using shell execute..
        /// </summary>
        internal static string ArgumentExceptionRedirectErrorAndShellExecuteSeleted {
            get {
                return ResourceManager.GetString("ArgumentExceptionRedirectErrorAndShellExecuteSeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect output may not be selected when using shell execute..
        /// </summary>
        internal static string ArgumentExceptionRedirectOutputAndShellExecuteSeleted {
            get {
                return ResourceManager.GetString("ArgumentExceptionRedirectOutputAndShellExecuteSeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed regular expression filter is invalid..
        /// </summary>
        internal static string ArgumentExceptionRenamedFilter {
            get {
                return ResourceManager.GetString("ArgumentExceptionRenamedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version does not support calling services..
        /// </summary>
        internal static string ArgumentExceptionThisVersionDoesNotSupportCallingServices {
            get {
                return ResourceManager.GetString("ArgumentExceptionThisVersionDoesNotSupportCallingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name may not be specified when using shell execute..
        /// </summary>
        internal static string ArgumentExceptionUserNameAndShellExecute {
            get {
                return ResourceManager.GetString("ArgumentExceptionUserNameAndShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than zero..
        /// </summary>
        internal static string ArgumentExceptionValueCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("ArgumentExceptionValueCannotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher working directory does not exist..
        /// </summary>
        internal static string ArgumentExceptionWorkingDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ArgumentExceptionWorkingDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null..
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments string is too long..
        /// </summary>
        internal static string ArgumentsStringIsTooLongException {
            get {
                return ResourceManager.GetString("ArgumentsStringIsTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to callService.
        /// </summary>
        internal static string ColumnCallService {
            get {
                return ResourceManager.GetString("ColumnCallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changedRegularExpressionFilter.
        /// </summary>
        internal static string ColumnChangedRegularExpressionFilter {
            get {
                return ResourceManager.GetString("ColumnChangedRegularExpressionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createdRegularExpressionFilter.
        /// </summary>
        internal static string ColumnCreatedRegularExpressionFilter {
            get {
                return ResourceManager.GetString("ColumnCreatedRegularExpressionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daemonName.
        /// </summary>
        internal static string ColumnDaemonName {
            get {
                return ResourceManager.GetString("ColumnDaemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletedRegularExpressionFilter.
        /// </summary>
        internal static string ColumnDeletedRegularExpressionFilter {
            get {
                return ResourceManager.GetString("ColumnDeletedRegularExpressionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directoryPollInterval.
        /// </summary>
        internal static string ColumnDirectoryPollInterval {
            get {
                return ResourceManager.GetString("ColumnDirectoryPollInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayFileSystemChange.
        /// </summary>
        internal static string ColumnDisplayFileSystemChange {
            get {
                return ResourceManager.GetString("ColumnDisplayFileSystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayFileSystemSearchError.
        /// </summary>
        internal static string ColumnDisplayFileSystemSearchError {
            get {
                return ResourceManager.GetString("ColumnDisplayFileSystemSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayFileSystemSearchProgress.
        /// </summary>
        internal static string ColumnDisplayFileSystemSearchProgess {
            get {
                return ResourceManager.GetString("ColumnDisplayFileSystemSearchProgess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        internal static string ColumnFilter {
            get {
                return ResourceManager.GetString("ColumnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filteredMode.
        /// </summary>
        internal static string ColumnFilteredMode {
            get {
                return ResourceManager.GetString("ColumnFilteredMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filteredModeFilterTimeout.
        /// </summary>
        internal static string ColumnFilteredModeFilterTimeout {
            get {
                return ResourceManager.GetString("ColumnFilteredModeFilterTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generateFileSystemEventsAtStartup.
        /// </summary>
        internal static string ColumnGenerateFileSystemEventsAtStartup {
            get {
                return ResourceManager.GetString("ColumnGenerateFileSystemEventsAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generatedEventFileNameRegularExpressionFilter.
        /// </summary>
        internal static string ColumnGenereatedEventFileNameRegularExpressionFilter {
            get {
                return ResourceManager.GetString("ColumnGenereatedEventFileNameRegularExpressionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includeSubdirectories.
        /// </summary>
        internal static string ColumnIncludeSubdirectories {
            get {
                return ResourceManager.GetString("ColumnIncludeSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internalBufferSize.
        /// </summary>
        internal static string ColumnInternalBufferSize {
            get {
                return ResourceManager.GetString("ColumnInternalBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logFileSystemChange.
        /// </summary>
        internal static string ColumnLogFileSystemChange {
            get {
                return ResourceManager.GetString("ColumnLogFileSystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logFileSystemSearchError.
        /// </summary>
        internal static string ColumnLogFileSystemSearchError {
            get {
                return ResourceManager.GetString("ColumnLogFileSystemSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logFileSystemSearchProgress.
        /// </summary>
        internal static string ColumnLogFileSystemSearchProgress {
            get {
                return ResourceManager.GetString("ColumnLogFileSystemSearchProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logProcessEnd.
        /// </summary>
        internal static string ColumnLogProcessEnd {
            get {
                return ResourceManager.GetString("ColumnLogProcessEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logProcessStart.
        /// </summary>
        internal static string ColumnLogProcessStart {
            get {
                return ResourceManager.GetString("ColumnLogProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifyAttribute.
        /// </summary>
        internal static string ColumnNotifyAttribute {
            get {
                return ResourceManager.GetString("ColumnNotifyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifyCreationTime.
        /// </summary>
        internal static string ColumnNotifyCreationTime {
            get {
                return ResourceManager.GetString("ColumnNotifyCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifyDirectoryName.
        /// </summary>
        internal static string ColumnNotifyDirectoryName {
            get {
                return ResourceManager.GetString("ColumnNotifyDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifyFileName.
        /// </summary>
        internal static string ColumnNotifyFileName {
            get {
                return ResourceManager.GetString("ColumnNotifyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifyLastAccess.
        /// </summary>
        internal static string ColumnNotifyLastAccess {
            get {
                return ResourceManager.GetString("ColumnNotifyLastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifyLastWrite.
        /// </summary>
        internal static string ColumnNotifyLastWrite {
            get {
                return ResourceManager.GetString("ColumnNotifyLastWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifySecurity.
        /// </summary>
        internal static string ColumnNotifySecurity {
            get {
                return ResourceManager.GetString("ColumnNotifySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifySize.
        /// </summary>
        internal static string ColumnNotifySize {
            get {
                return ResourceManager.GetString("ColumnNotifySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string ColumnPath {
            get {
                return ResourceManager.GetString("ColumnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pollDirectory.
        /// </summary>
        internal static string ColumnPollDirectory {
            get {
                return ResourceManager.GetString("ColumnPollDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processArguments.
        /// </summary>
        internal static string ColumnProcessArguments {
            get {
                return ResourceManager.GetString("ColumnProcessArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processArgumentsChangeTypeEscapeString.
        /// </summary>
        internal static string ColumnProcessArgumentsChangeTypeEscapeString {
            get {
                return ResourceManager.GetString("ColumnProcessArgumentsChangeTypeEscapeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processArgumentsFileNameEscapeString.
        /// </summary>
        internal static string ColumnProcessArgumentsFileNameEscapeString {
            get {
                return ResourceManager.GetString("ColumnProcessArgumentsFileNameEscapeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processArgumentsOldFileNameEscapeString.
        /// </summary>
        internal static string ColumnProcessArgumentsOldFileNameEscapeString {
            get {
                return ResourceManager.GetString("ColumnProcessArgumentsOldFileNameEscapeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processBatchSize.
        /// </summary>
        internal static string ColumnProcessBatchSize {
            get {
                return ResourceManager.GetString("ColumnProcessBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processCreateNoWindow.
        /// </summary>
        internal static string ColumnProcessCreateNoWindow {
            get {
                return ResourceManager.GetString("ColumnProcessCreateNoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processDelay.
        /// </summary>
        internal static string ColumnProcessDelay {
            get {
                return ResourceManager.GetString("ColumnProcessDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processDomain.
        /// </summary>
        internal static string ColumnProcessDomain {
            get {
                return ResourceManager.GetString("ColumnProcessDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processFileMustExist.
        /// </summary>
        internal static string ColumnProcessFileMustExist {
            get {
                return ResourceManager.GetString("ColumnProcessFileMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processFileName.
        /// </summary>
        internal static string ColumnProcessFileName {
            get {
                return ResourceManager.GetString("ColumnProcessFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processLoadUserProfile.
        /// </summary>
        internal static string ColumnProcessLoadUserProfile {
            get {
                return ResourceManager.GetString("ColumnProcessLoadUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processLockFile.
        /// </summary>
        internal static string ColumnProcessLockFile {
            get {
                return ResourceManager.GetString("ColumnProcessLockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processLockFileLastWriteDelay.
        /// </summary>
        internal static string ColumnProcessLockFileLastWriteDelay {
            get {
                return ResourceManager.GetString("ColumnProcessLockFileLastWriteDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processLockFileRetries.
        /// </summary>
        internal static string ColumnProcessLockFileRetries {
            get {
                return ResourceManager.GetString("ColumnProcessLockFileRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processLockFileRetriesQueueLimit.
        /// </summary>
        internal static string ColumnProcessLockFileRetriesQueueLimit {
            get {
                return ResourceManager.GetString("ColumnProcessLockFileRetriesQueueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processMaxWaitTime.
        /// </summary>
        internal static string ColumnProcessMaxWaitTime {
            get {
                return ResourceManager.GetString("ColumnProcessMaxWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processPassword.
        /// </summary>
        internal static string ColumnProcessPassword {
            get {
                return ResourceManager.GetString("ColumnProcessPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processRedirectStandardError.
        /// </summary>
        internal static string ColumnProcessRedirectStandardError {
            get {
                return ResourceManager.GetString("ColumnProcessRedirectStandardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processRedirectStandardOutput.
        /// </summary>
        internal static string ColumnProcessRedirectStandardOutput {
            get {
                return ResourceManager.GetString("ColumnProcessRedirectStandardOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processSynchronizedExecution.
        /// </summary>
        internal static string ColumnProcessSynchronizedExecution {
            get {
                return ResourceManager.GetString("ColumnProcessSynchronizedExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processUseChangeTypeAsArgument.
        /// </summary>
        internal static string ColumnProcessUseChangeTypeAsArgument {
            get {
                return ResourceManager.GetString("ColumnProcessUseChangeTypeAsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processUseFileNameAsArgument.
        /// </summary>
        internal static string ColumnProcessUseFileNameAsArgument {
            get {
                return ResourceManager.GetString("ColumnProcessUseFileNameAsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processUseOldFileNameAsArgument.
        /// </summary>
        internal static string ColumnProcessUseOldFileNameAsArgument {
            get {
                return ResourceManager.GetString("ColumnProcessUseOldFileNameAsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processUserName.
        /// </summary>
        internal static string ColumnProcessUserName {
            get {
                return ResourceManager.GetString("ColumnProcessUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processUseShellExecute.
        /// </summary>
        internal static string ColumnProcessUseShellExecute {
            get {
                return ResourceManager.GetString("ColumnProcessUseShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processVerb.
        /// </summary>
        internal static string ColumnProcessVerb {
            get {
                return ResourceManager.GetString("ColumnProcessVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processWindowStyle.
        /// </summary>
        internal static string ColumnProcessWindowStyle {
            get {
                return ResourceManager.GetString("ColumnProcessWindowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processWorkingDirectory.
        /// </summary>
        internal static string ColumnProcessWorkingDirectory {
            get {
                return ResourceManager.GetString("ColumnProcessWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recycleFileWatcher.
        /// </summary>
        internal static string ColumnRecycleFileWatcher {
            get {
                return ResourceManager.GetString("ColumnRecycleFileWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recycleInterval.
        /// </summary>
        internal static string ColumnRecycleInterval {
            get {
                return ResourceManager.GetString("ColumnRecycleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to renamedRegularExpressionFilter.
        /// </summary>
        internal static string ColumnRenamedRegularExpressionFilter {
            get {
                return ResourceManager.GetString("ColumnRenamedRegularExpressionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startDaemon.
        /// </summary>
        internal static string ColumnStartDaemon {
            get {
                return ResourceManager.GetString("ColumnStartDaemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startProcess.
        /// </summary>
        internal static string ColumnStartProcess {
            get {
                return ResourceManager.GetString("ColumnStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streamFile.
        /// </summary>
        internal static string ColumnStreamFile {
            get {
                return ResourceManager.GetString("ColumnStreamFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribeToBufferErrorEvent.
        /// </summary>
        internal static string ColumnSubscribeToBufferErrorEvent {
            get {
                return ResourceManager.GetString("ColumnSubscribeToBufferErrorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribeToChangedEvent.
        /// </summary>
        internal static string ColumnSubscribeToChangedEvent {
            get {
                return ResourceManager.GetString("ColumnSubscribeToChangedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribeToCreatedEvent.
        /// </summary>
        internal static string ColumnSubscribeToCreatedEvent {
            get {
                return ResourceManager.GetString("ColumnSubscribeToCreatedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribeToDeletedEvent.
        /// </summary>
        internal static string ColumnSubscribeToDeletedEvent {
            get {
                return ResourceManager.GetString("ColumnSubscribeToDeletedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribeToRenamedEvent.
        /// </summary>
        internal static string ColumnSubscribeToRenamedEvent {
            get {
                return ResourceManager.GetString("ColumnSubscribeToRenamedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tryRenameFile.
        /// </summary>
        internal static string ColumnTryRenameFile {
            get {
                return ResourceManager.GetString("ColumnTryRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tryRenameFileRetries.
        /// </summary>
        internal static string ColumnTryRenameFileRetries {
            get {
                return ResourceManager.GetString("ColumnTryRenameFileRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fWatcherConfig.
        /// </summary>
        internal static string DatasetName {
            get {
                return ResourceManager.GetString("DatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string FileNotFoundException {
            get {
                return ResourceManager.GetString("FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System generated.
        /// </summary>
        internal static string FileSystemChangeTypeSystemGenerated {
            get {
                return ResourceManager.GetString("FileSystemChangeTypeSystemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher configuration cannot be added..
        /// </summary>
        internal static string InvalidOperationExceptionConfigurationCannotBeAdded {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionConfigurationCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher configuration cannot be loaded..
        /// </summary>
        internal static string InvalidOperationExceptionConfigurationCannotBeLoaded {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionConfigurationCannotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher configuration cannot be removed..
        /// </summary>
        internal static string InvalidOperationExceptionConfigurationCannotBeRemoved {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionConfigurationCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher configuration cannot be updated..
        /// </summary>
        internal static string InvalidOperationExceptionConfigurationCannotBeUpdated {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionConfigurationCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard error cannot be redirected if using shell execute..
        /// </summary>
        internal static string InvalidOperationExceptionError {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file name specified..
        /// </summary>
        internal static string InvalidOperationExceptionFileName {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher is already started..
        /// </summary>
        internal static string InvalidOperationExceptionFileWatcherAlreadyStarted {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileWatcherAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher is already stopped..
        /// </summary>
        internal static string InvalidOperationExceptionFileWatcherAlreadyStopped {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileWatcherAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher controller is running..
        /// </summary>
        internal static string InvalidOperationExceptionFileWatcherControllerIsRunning {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileWatcherControllerIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watcher controller is stopping..
        /// </summary>
        internal static string InvalidOperationExceptionFileWatcherControllerIsStopping {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileWatcherControllerIsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File watchers are already stopped..
        /// </summary>
        internal static string InvalidOperationExceptionFileWatchersAlreadyStopped {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileWatchersAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file watcher was starting and it cannot be stopped..
        /// </summary>
        internal static string InvalidOperationExceptionFileWatchersIsStarting {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionFileWatchersIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard input cannot be redirected if using shell execute..
        /// </summary>
        internal static string InvalidOperationExceptionInput {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enabled file watchers..
        /// </summary>
        internal static string InvalidOperationExceptionNoEnabledFileWatchers {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionNoEnabledFileWatchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard output cannot be redirected if using shell execute..
        /// </summary>
        internal static string InvalidOperationExceptionOutput {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be used if using shell execute..
        /// </summary>
        internal static string InvalidOperationExceptionPassword {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous execution cannot be set if file watceher controller is active..
        /// </summary>
        internal static string InvalidOperationExceptionSynchronousExecutionCannotBeSet {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionSynchronousExecutionCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be used if using shell execute..
        /// </summary>
        internal static string InvalidOperationExceptionUserName {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileWatcherController.
        /// </summary>
        internal static string ObjectNameFileWatcherContoller {
            get {
                return ResourceManager.GetString("ObjectNameFileWatcherContoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
